"""Markdown report matching whitepaper structure."""

from __future__ import annotations

from pathlib import Path

from ..models import Finding, ScanReport, Status


def render(report: ScanReport, output_path: Path | None = None) -> str:
    """Render report as Markdown."""
    report.compute_summary()
    s = report.summary
    lines: list[str] = []

    lines.append("# OpenClaw Security Audit Report\n")
    lines.append(f"**Target:** `{report.target}`  ")
    lines.append(f"**Context:** {report.context_type}  ")
    lines.append(f"**Total Checks:** {s['total_checks']}\n")

    # Executive summary
    fail_n = s["by_status"].get("FAIL", 0)
    warn_n = s["by_status"].get("WARN", 0)
    pass_n = s["by_status"].get("PASS", 0)

    lines.append("## Executive Summary\n")
    if fail_n == 0 and warn_n == 0:
        lines.append("All security checks passed. The deployment meets the "
                      "CSAI hardening baseline.\n")
    else:
        lines.append(f"The audit identified **{fail_n} failure(s)** and "
                      f"**{warn_n} warning(s)** across {s['total_checks']} checks.\n")

    lines.append("| Status | Count |")
    lines.append("|--------|-------|")
    for st in ["FAIL", "WARN", "PASS", "SKIP"]:
        count = s["by_status"].get(st, 0)
        if count:
            lines.append(f"| {st} | {count} |")
    lines.append("")

    # Severity breakdown
    if fail_n or warn_n:
        lines.append("### Severity Breakdown\n")
        lines.append("| Severity | Count |")
        lines.append("|----------|-------|")
        for sev in ["CRITICAL", "HIGH", "MEDIUM", "LOW"]:
            count = s["by_severity"].get(sev, 0)
            if count:
                lines.append(f"| {sev} | {count} |")
        lines.append("")

    # Findings by category
    by_cat: dict[str, list[Finding]] = {}
    for f in report.findings:
        by_cat.setdefault(f.category, []).append(f)

    for cat in sorted(by_cat.keys()):
        findings = by_cat[cat]
        cat_fails = [f for f in findings if f.status == Status.FAIL]
        cat_warns = [f for f in findings if f.status == Status.WARN]

        if not cat_fails and not cat_warns:
            continue

        lines.append(f"## {cat}\n")

        for f in cat_fails + cat_warns:
            icon = "🔴" if f.status == Status.FAIL else "🟡"
            lines.append(f"### {icon} {f.check_id}: {f.title}\n")
            lines.append(f"**Severity:** {f.severity.value}  ")
            lines.append(f"**Status:** {f.status.value}\n")
            lines.append(f"{f.description}\n")

            if f.evidence:
                lines.append(f"**Evidence:** `{f.evidence}`\n")
            if f.file_path:
                lines.append(f"**File:** `{f.file_path}`\n")
            if f.recommendation:
                lines.append(f"**Recommendation:** {f.recommendation}\n")

            if f.frameworks:
                fm = f.frameworks.to_dict()
                if fm:
                    lines.append("**Framework Mappings:**\n")
                    for k, v in fm.items():
                        if isinstance(v, list):
                            lines.append(f"- {k}: {', '.join(v)}")
                        else:
                            lines.append(f"- {k}: {v}")
                    lines.append("")

    # Passing checks summary
    passed = [f for f in report.findings if f.status == Status.PASS]
    if passed:
        lines.append("## Passing Checks\n")
        lines.append("| Check ID | Title |")
        lines.append("|----------|-------|")
        for f in passed:
            lines.append(f"| {f.check_id} | {f.title} |")
        lines.append("")

    # Footer
    lines.append("---\n")
    lines.append("*Generated by openclaw-audit v1.0.0 — "
                 "CSAI OpenClaw Hardening Guide Compliance Scanner*\n")

    text = "\n".join(lines)
    if output_path:
        output_path.write_text(text, encoding="utf-8")
    return text
